### ISSUE TITLE
Finish the colorbar implementation.

### ISSUE THREAD

**Issue by tshead2** [sandialabs/toyplot#103]
The current ColorBar mark is pretty unusable.  Some fixes, in no particular order:

- [x] Should be implemented using the new toyplot.axes.Axis object.
- [x] Should be possible to construct color bars at the canvas level, not just axes.
- [x] We should provide an option to create color bars as part of a matrix visualization.
- [x] Need to synchronize the API with changes elsewhere.
- [x] It should be possible to create horizontal color bars.

**Comment by gavinhodge** [comment]
Could I please add to this? It would be nice to do grouped color bar charts as well, showing multiple categories per tick mark.

Here's a rather advanced example: http://bl.ocks.org/mbostock/3887051

I'm happy to raise as a separate issue if you like.

**Comment by tshead2** [comment]
@gavinhodge - Reasonable request, but it does belong in a separate issue - this one is addressing the current mark for showing the mapping between data values and colors, so only tangentially related to bar plots.

Many thanks!
Tim

**Comment by gavinhodge** [comment]
I'd love to be familiar enough with the code to attempt this, but I'm a long way off being able to do that. No worries, I'll create a separate issue!

**Comment by tshead2** [comment]
Closed in 8615ba4ef137eaa60575695d0018f0c301bfc987
