### ISSUE TITLE
2 Y-Axes with different values?

### ISSUE THREAD

**Issue by johanndt** [sandialabs/toyplot#104]
Hi, I'm very new with toyplot and have been struggling with something which I think should be quite easy.

I'm trying to plot bars and a line in the same chart.

I created 2 axes on the same canvas, and did `bars()` on the one, and `plots()` on the other:

![image](https://cloud.githubusercontent.com/assets/7507499/10934003/f186cf7c-8330-11e5-813c-60db0095fc0c.png)

However, what if the 2 y-axes have different min and max values/ranges? I'm trying to display 2 different y axes, but it's not working for me.

I've looked into `axes.y.spine.position = "high"`, but that only moves the spine. Then I tried to move the labels as well with `axes.y.ticks.labels.offset = ??`, but it's tricky to compute where they should be.

Is there a way to just move the whole y-axis to the right? Or have 2 y-axis next to each other with readable labels? I tried `padding` as well, but that appears to move the actual plotted data too.

Like I said, I think I'm missing something obvious! Thanks!

**Comment by tshead2** [comment]
@johanndt - in this case, it isn't you, it's toyplot ... if you want your plots to share the same domain, it's simple - just create one set of axes and call bars() and plot().  However, for your case where you have separate domains, there isn't a convenient way to position multiple axes.  It's been on my TODO list for a long time to add some additional positioning parameters to the axes to support this - I'll see if I can't get something in place for you this week.

Cheers,
Tim

**Comment by johanndt** [comment]
Thanks Tim! I really appreciate you having a look at this so quickly.

I'm trying to use toyplot in some custom reporting for a client right now, so I'm happy to spend some time to help with a fix too. I'm in the Australian timezone though.

Johann

**Comment by johanndt** [comment]
So I've been playing around with the notebook you committed and was able to move the second y axis to the right if this helps you at all to do it more properly.

Now to align the x-axis for bars and lines...

https://gist.github.com/johanndt/cd961901c1977763fb70

**Comment by johanndt** [comment]
Hi Tim,

I got the x axis now lining up too. So here's a gist of the end-result I'm looking for. But it feels kinda patchy the way I did it. :-)

https://gist.github.com/johanndt/b4855e7484f7b5fc5d4e

Thanks
Johann

**Comment by tshead2** [comment]
Johann:

Thanks for the examples!  FYI, the behavior of bars() by default is to give them a width of "1" and center them over integer X values, so a different way to align the X axis would be to specify xmin=-0.5 and xmax=10.5 for the plot axes.

In any case, there are three new features that I have in mind to make things easier:

* Better control over the positioning of the axes ticks / labels / spines.  The ticks and labels will follow the spine when it's moved, and will have explicit controls to place them relative to the spine (what you're doing with baseline-shift in your example).

* A way to explicitly link two sets of axis dimensions, so they share a domain (what you're doing manually with the X axes in your example).

* Some convenience functions to make it easier to work with dual axes - i.e. a method of one set of axes that creates the other, with the spine positioned correctly and the other dimension linked.

Cheers,
Tim

**Comment by johanndt** [comment]
That sounds great Tim, and thanks for the tip on the X values.

I just did the examples to give myself some peace of mind that what we'd need to do is possible. So I will now happily wait for the convenience functions. :-)

Cheers,
Johann

**Comment by tshead2** [comment]
Johann:

So, everything is up-and-running in master, see http://toyplot.readthedocs.org/en/latest/cartesian-axes.html for a writeup, and let me know what you think.

FWIW, getting this working was a bigger change than I had anticipated, but it's timely - it will solve several other problems as well.

Cheers,
Tim

**Comment by johanndt** [comment]
Thanks so much Tim!

We will try it this week and I'll let you know how it goes. 

Cheers
Johann
