### ISSUE TITLE
display in spyder with qt fails

### ISSUE THREAD

**Issue by dacoex** [sandialabs/toyplot#140]
I tried to display plots in the ipython qt consoled embedded in spyder using

[displays](http://toyplot.readthedocs.org/en/stable/rendering.html?highlight=rendering#displays)

I get this error:

`TypeError: QWebView.setHtml(str, QUrl baseUrl=QUrl()): argument 1 has unexpected type 'bytes'`

**Comment by tshead2** [comment]
@dacoex: Thanks for the heads-up!  Could you pass along the versions for Python, Spyder, and Qt in this case?  I'm betting that this is a Python 3 thing, as I've never gotten Qt 5 working with Python 3.

Many thanks,
Tim

**Comment by tshead2** [comment]
Also, it would be fair to say that `toyplot.browser.show()` provides the same functionality with much better portability.
