### ISSUE TITLE
Update numpy version to 1.9+

### ISSUE THREAD

**Issue by johanndt** [sandialabs/toyplot#149]
I noticed that toyplot/data.py in __init__ line 95 uses the `return_counts` parameter in `numpy.unique`. This was only added in numpy 1.9.0 and causes a TypeError when trying to add a Table with older versions.

Currently setup.py lists `numpy>=1.7`

Just of note is that standard Ubuntu and Debian only include packages for numpy 1.8.

**Comment by tshead2** [comment]
@johanndt - excellent catch!  After playing around with different numpy versions, I've changed the requirement to 1.8 (Toyplot seems horribly broken on 1.7), rewritten the code that depended on 1.9 and - most importantly - updated the travis-ci build to use 1.8 for testing, so this shouldn't happen again.

Many thanks, this is the kind of thing that causes bad experiences for new users.

Cheers,
Tim
