### ISSUE TITLE
Add warnings to the readthedocs master branch to avoid confusing end-users.

### ISSUE THREAD

**Issue by pybokeh** [sandialabs/toyplot#155]
Hello, I've installed toyplot via pip.  I am using python version 3.5.1.

When I attempt to do the examples, I get this error in the title.

**Comment by tshead2** [comment]
@pybokeh: where are you getting your examples?  If you installed toyplot from pip, you should have version 0.11, which uses "canvas.axes()".  Version 0.12, which is unreleased, changes that to "canvas.cartesian()", but the documentation at http://toyplot.readthedocs.org correctly matches version 0.11.

Cheers,
Tim

**Comment by pybokeh** [comment]
@tshead2 Oh wow you're right.  I originally went to docs from google search and it took me to latest docs instead of stable docs.  Sorry about that!

**Comment by tshead2** [comment]
@pybokeh: Not at all, it's good to know that that's happening - I'll see if I can think of a way to avoid confusion in the future - maybe a banner at the top of each documentation page for the unreleased docs.  
Thanks!
Tim

**Comment by tshead2** [comment]
I keep revisiting this, and keep not figuring-out a way to do it.
