### ISSUE TITLE
Accept standard Python sequences of numbers for color

### ISSUE THREAD

**Issue by fnorf** [sandialabs/toyplot#165]
I can pass normal Python lists for x, y and size like in this minimal example:

```
import numpy
import toyplot
x = [1, 2]
y = [1, 2]
size = [10, 25]

canvas = toyplot.Canvas()
axes = canvas.cartesian()
mark = axes.scatterplot(x, y, size=size)
```

But for specifying the color I can not. The tutorial says "If you pass a sequence of scalar values" which to me includes numeric lists or tuples. By trail and error I figured out to use numpy.array instead.

Please support normal Python sequences for the color mapping just like they can be used for the other arguments. :)

**Comment by tshead2** [comment]
I'll look into this.  Also, if you haven't already, take a look at http://toyplot.readthedocs.io/en/stable/colors.html and http://toyplot.readthedocs.io/en/stable/color-mapping.html in the documentation.

Cheers,
Tim
