### ISSUE TITLE
Make tables convenient to copy and paste

### ISSUE THREAD

**Issue by kannes** [sandialabs/toyplot#177]
If I copy the first table in http://toyplot.readthedocs.io/en/stable/table-coordinates.html I end up with a single-line without any separators:

`STATIONSTATION_NAMEDATETMAXTMINTOBSGHCND:USC00294366JEMEZ DAM NM US2013010139-72-67GHCND:USC00294366JEMEZ DAM NM US201301020-133-133GHCND:USC00294366JEMEZ DAM NM US2013010311-139-89GHCND:USC00294366JEMEZ DAM NM US2013010411-139-89GHCND:USC00294366JEMEZ DAM NM US2013010522-144-111GHCND:USC00294366JEMEZ DAM NM US2013010644-122-100GHCND:USC00294366JEMEZ DAM NM US2013010756-122-11GHCND:USC00294366JEMEZ DAM NM US20130108100-83-78GHCND:USC00294366JEMEZ DAM NM US2013010972-83-33GHCND:USC00294366JEMEZ DAM NM US2013011189-5022`

It would be fantastic if one would get output that was ready to be pasted to another tabular/spreadsheet application or to a csv/tsv file. Maybe linebreaks plus tabs?

**Comment by tshead2** [comment]
Not sure if you're aware of this already, but you can RMB click on a table to export its contents as a CSV file, see http://toyplot.readthedocs.io/en/stable/interaction.html#data-export for details.

If you already knew that and just prefer using the clipboard, I don't know how much ability we have to customize browser behavior in this case.  Part of the tradeoff here is that a Toyplot table is a graphic, not an HTML table, so the browser can't treat it as such.

**Comment by kannes** [comment]
Ah, I did not realise that it was an SVG and neither that rightclick did things. Thanks! I'd say close this if there is no easy way. I thought it was a normal HTML table :)

**Comment by tshead2** [comment]
It turns-out that HTML5 includes an API for working with the clipboard that might be easy to use, so I will leave this as a feature request.

**Comment by tshead2** [comment]
I haven't been able to get the clipboard API working reliably, so going to close this for the time being.
