### ISSUE TITLE
Document the relationship between locators, ticks, and the displayed domain.

### ISSUE THREAD

**Issue by kciosek** [sandialabs/toyplot#180]
The following code produces a plot with x axis ranging from 0 to 115 while I think it should go from 15 to 115.
Apologies in advance if I am just misunderstanding the API.
```
import numpy
import toyplot
import toyplot.pdf

canvas = toyplot.Canvas(width=400, height=300)
axes = canvas.cartesian()
SHIFT = 15 
x_vals = numpy.arange(SHIFT, SHIFT + 100)
mp = axes.plot(x_vals, x_vals)
axes.x.domain.min=x_vals[0]

# Problem: x axis starts from 0 but should start from 15
toyplot.pdf.render(canvas, "test.pdf")
```

**Comment by tshead2** [comment]
@kciosek - what's happening here is that by default Toyplot produces "nice" tick labels using "round" numbers, and the domain is expanded to contain them - in your case, a tick at zero.  There are several ways you could override this behavior:

    # Continue to use the default tick locator, but only generate ticks inside the data domain:
    axes.x.ticks.locator = toyplot.locator.Extended(only_inside=True)

    # Use a Uniform tick locator, which generates ticks between the min and max data domain values:
    axes.x.ticks.locator = toyplot.locator.Uniform()

    # Use an Explicit tick locator, which gives you carte blanche to create just the ticks you want:
    axes.x.ticks.locator = toyplot.locator.Explicit([15, 37, 114])

I'll update the documentation to make this clearer next release.

Cheers,
Tim

**Comment by kciosek** [comment]
Thanks. That's very useful.
