### ISSUE TITLE
Is it possible to render toyplot as subplot of matplotlib gridspec?

### ISSUE THREAD

**Issue by yech1990** [sandialabs/toyplot#188]
https://matplotlib.org/users/gridspec.html

![image](https://user-images.githubusercontent.com/5415510/46655331-e7aebe80-cbdd-11e8-9a40-69707138a266.png)

**Comment by tshead** [comment]
You can create a layout like this one in toyplot quite easily, see https://toyplot.readthedocs.io/en/stable/canvas-layout.html for details.  However, I'm not sure if that's what you're asking ... are you trying to embed a toyplot plot within a matplotlib figure?

Cheers,
Tim

**Comment by yech1990** [comment]
thanks Tim,
I am trying to embed a toyplot plot within a matplotlib figure.

**Comment by tshead2** [comment]
Definitely an unusual request :)

The challenge is that the toyplot and marplotlib backends are so different.  Off the top of my head, you could use the `toyplot.png` backend to render a plot to an image, and then embed the image in your figure, but that eliminates most of Toyplot's advantages in quality and interaction.

Out of curiosity, what is matplotlib doing that Toyplot isn't?

Cheers,
Tim
