### ISSUE TITLE
Scatterplots does not account for range of data.

### ISSUE THREAD

**Issue by Xparx** [sandialabs/toyplot#190]
Hello,

Python 3.6.7

toyplot.__version__
'0.18.0'
np.__version__
'1.15.4'

I wanted to play around with toyplot but ran in to a weird issue that I can't seem to figure out.
I have a numpy array I want to make a scatter plot with available [here](https://drive.google.com/open?id=1r0bpwweZ9dPFLfQR9-FORQss0x23WdrE)

if I use this for plotting 

```
canvas = toyplot.Canvas(width=400)
axes = canvas.cartesian()
ccc = np.load("scatterdata.npy")
mark = axes.scatterplot(ccc[:,0], ccc[:,1], title="PCA components")
toyplot.html.render(canvas, "figure1.html")
```
I get this weird behavior where x and y range only go from -0.5 to 0.5 shown in this html.
https://drive.google.com/open?id=1KzWbwpjyfahBOxFH5OsWbQ9ZXQ9rpnn_

if I instead generate data with numpy
```
a = np.random.randn(1000)
b = np.random.randn(1000)
a = a/np.abs(a).max()
b = b/np.abs(b).max()
canvas = toyplot.Canvas(width=400)
axes = canvas.cartesian()
mark = axes.scatterplot(a, b, title="test")
toyplot.html.render(canvas, "figure1.html")
```

I can't figure out what is different with these two approaches. Looking at the data type they both look the same to me.

**Comment by tshead2** [comment]
@Xparx - I'm also using Python 3.6.7 and numpy 1.15.4, but I'm not able to reproduce this problem - when I run your data and code, the domain is correct for both axes.  The only way I know of to produce the outcome in your link would be to explicitly specify *xmin, xmax, ymin, ymax* when you create the axes.

Toyplot does default to a [-0.5, 0.5] domain, but that default only applies if you create axes and don't add any data to them.  You might check your data for nans, infinities, or other weirdness.  When I examine it I get the following:

```
>>> import numpy
>>> ccc = numpy.load("scatterdata.npy")
>>> ccc.shape
(885, 2)
>>> ccc.min(axis=0)
array([-0.74800959, -0.59287314])
>>> ccc.max(axis=0)
array([1.        , 0.94738604])
>>> numpy.count_nonzero(numpy.isnan(ccc))
0
>>> numpy.count_nonzero(numpy.isinf(ccc))
0

```

**Comment by Xparx** [comment]
Yes, you are right. When I load my data the way I present here the issue is gone for some reason. The original data is loaded from an .h5ad file with the anndata https://anndata.readthedocs.io/en/latest. It's just a very odd issue. (see note at the bottom)

For some reason my followup post with my example image is gone and I also noted that the link to my html file doesn't include the underscore at the end when clicking it so it fails. Perhaps [this](https://drive.google.com/open?id=1KzWbwpjyfahBOxFH5OsWbQ9ZXQ9rpnn_) works bettter.

Anyway, I didn't find the min max arguments before so I couldn't fix it manually. Thanks for the hint.
I thought it might have been an issue with how the data was encoded.

# Note:
Ok, Now when I'm redoing it with my original data it looks like it works as intended. I'm so confused.
Could it be that I plotted on an already populated canvas or axes?
I will do some further work and if the issue pops up again so I can track it down I will get back here with more helpful info.

**Comment by tshead2** [comment]
Toyplot objects (canvas, axes, etc) aren’t meant to be re-used - when they’re rendered, they undergo a process called “finalization” that freezes various bits of state, including the axis domain(s).  So, you could produce your problem with some variation of the following:

```
import numpy
import toyplot.html

canvas = toyplot.Canvas(width=400)
axes = canvas.cartesian()
toyplot.html.render(canvas, "test1.html")
data = numpy.random.normal(size=(1000, 2))
axes.scatterplot(data[:,0], data[:,1])
toyplot.html.render(canvas, "test2.html")
```

… in this example, the first call to render() finalizes the domain at [-0.5, 0.5] because there’s no data.  The second call to render() displays the data, but the domain is already frozen.  I could see this happening if you’re debugging code, playing-around in the interactive interpreter, or running Jupyter cells out of order.  There’s no warning because it’s perfectly reasonable to render a canvas using multiple back-ends, but I could imagine warning / raising an exception if you try to change the canvas state between renders.

Cheers,
Tim

**Comment by Xparx** [comment]
Thanks for that explanation! That sounds very plausible. I could see myself doing something like that by accident just trying out the commands. I will keep my eyes open for that.

**Comment by tshead2** [comment]
Tidying-up.
