### ISSUE TITLE
How to color scatterplots with categorical colors?

### ISSUE THREAD

**Issue by Xparx** [sandialabs/toyplot#191]
Hi,

I'm trying to colorize my scatterplots with categorical data with specific colors.
I have these colors in an array with hex color values
`palette = np.array(['#9467bd', '#d62728', '#E6D812', '#2ca02c', '#1f77b4', '#ff7f0e'], dtype='<U7')`

now I have an array of strings (which I can also convert to integers) of the assignment of what color belong to each data points

```
ndatap = 10
color = np.random.randint(0,6, ndatap)

canvas = toyplot.Canvas(width=900, height=300)
axes = canvas.cartesian(grid=(1, 3, 0))
x = np.random.randn(1,ndatap)
y = np.random.randn(1,ndatap)
mark = axes.scatterplot(x, y, color=(color, palette))
```

I found a similar example in the tutoria [here](https://toyplot.readthedocs.io/en/stable/tutorial.html) but I'm it's not working for my specific setup. I'm guessing it's an issue of the hex colors in palette but I'm not sure. 
Can I use hexcolor in toyplot (it looks like treeplot supports it https://toytree.readthedocs.io/en/latest/TipLabels.html?highlight=hex so I'm guessing it should be possible) or should I go about this in some other way?

**Comment by Xparx** [comment]
I dug a bit deeper and found that I can convert my hex to rgba and put them in a palette.
```
clrs = np.array(['#9467bd', '#d62728', '#E6D812', '#2ca02c', '#1f77b4', '#ff7f0e'])
palette = toyplot.color.Palette([toyplot.color.css(i) for i in clrs])
```
Doing this generates the same issue I think as before with the code above,
```
IndexErrorTraceback (most recent call last)
<ipython-input-280-0c03567c2417> in <module>
     35 axes.y.ticks.labels.show = False
     36 
---> 37 toyplot.html.render(canvas, "figure1.html")
     38 toyplot.png.render(canvas, "figure1.png")

~/.virtualenvs/default/lib/python3.6/site-packages/toyplot/html.py in render(canvas, fobj, animation, style)
    328 
    329     # Render the canvas.
--> 330     _render(canvas, context.copy(parent=root_xml)) # pylint: disable=no-value-for-parameter
    331 
    332     # Return / write the results.

~/.virtualenvs/default/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    276             self._cache[types] = func
    277         try:
--> 278             return func(*args, **kwargs)
    279 
    280         except MDNotImplementedError:

~/.virtualenvs/default/lib/python3.6/site-packages/toyplot/html.py in _render(canvas, context)
    794     # Render everything on the canvas.
    795     for child in canvas._children:
--> 796         _render(canvas, child._finalize(), context.copy(parent=svg_xml))
    797 
    798     # Create a container for any Javascript code.

~/.virtualenvs/default/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    276             self._cache[types] = func
    277         try:
--> 278             return func(*args, **kwargs)
    279 
    280         except MDNotImplementedError:

~/.virtualenvs/default/lib/python3.6/site-packages/toyplot/html.py in _render(canvas, axes, context)
   1939 
   1940     for child in axes._children:
-> 1941         _render(axes, child._finalize(), context.copy(parent=children_xml))
   1942 
   1943     if axes._show:

~/.virtualenvs/default/lib/python3.6/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    276             self._cache[types] = func
    277         try:
--> 278             return func(*args, **kwargs)
    279 
    280         except MDNotImplementedError:

~/.virtualenvs/default/lib/python3.6/site-packages/toyplot/html.py in _render(axes, mark, context)
   3050                 dstyle = toyplot.style.combine(
   3051                     {
-> 3052                         "fill": toyplot.color.to_css(dfill),
   3053                         "stroke": toyplot.color.to_css(dstroke),
   3054                         "opacity": dopacity,

~/.virtualenvs/default/lib/python3.6/site-packages/toyplot/color.py in to_css(color)
   3182     css: :class:`str` containing a CSS color value.
   3183       """
-> 3184     return "rgba(%.1f%%,%.1f%%,%.1f%%,%.3f)" % (color["r"] * 100, color["g"] * 100, color["b"] * 100, color["a"])
   3185 
   3186 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
now it looks like it's actually not until I try to write the plot to file that the error appears.
```
toyplot.html.render(canvas, "figure1.html")
```

**Comment by Xparx** [comment]
After some more fiddling I decided to plot all categories separately which I think is the correct solution.

my corrent solution:
```
def color2dots(axes, data, label, color):
    mark = axes.scatterplot(data[:,0], data[:,1], color=color, opacity=1.0)
    return mark

cmapper = {k: toyplot.color.css(v) for k,v in mapper.items()}

marks = {}
for label, color in cmapper.items():
    data = pcaproj[(datalabels == label).tolist(), :]    
    marks[label] = color2dots(axes, data, label, color)
```
where `mapper` is a dictionary with category keys and hexcolor as values and `data` is my x and y values. 

Sorry for the noise.

**Comment by tshead** [comment]
@Xparx : No problem!  Here's a version of your original code that works:

```
import numpy as np
import toyplot

palette = toyplot.color.Palette(['#9467bd', '#d62728', '#E6D812', '#2ca02c', '#1f77b4', '#ff7f0e'])
colormap = toyplot.color.CategoricalMap(palette)

ndatap = 10
color = np.random.randint(0,6, ndatap)

canvas = toyplot.Canvas(width=900, height=300)
axes = canvas.cartesian(grid=(1, 3, 0))
x = np.random.randn(ndatap)
y = np.random.randn(ndatap)
mark = axes.scatterplot(x, y, color=(color, colormap))
```

I had to make a couple of changes.  First, Toyplot makes an explicit distinction between a color *palette* (which is literally just an ordered collection of colors) and a color *map* (which can map from data values to colors).  You always have to provide a *map* to control how your data is colored.  Palettes are just an implementation detail, which I'm leaning towards removing from the public API altogether, to avoid this sort of confusion.

Second your x and y arrays weren't the correct shapes.  x has to be a 1D array; y can be a matching 1D array, or a 2D array containing one column per data series.

Cheers,
Tim

**Comment by tshead** [comment]
You can pass a string or an array of strings to the `color` parameter, yes.  See [color mapping](https://toyplot.readthedocs.io/en/stable/color-mapping.html) for details on how you can pass a single color, per-series colors, or per-datum colors.

If you add a scatterplot mark to a legend, you’ll get the first marker from each series, which is the right thing in simple situations; if you’re coloring individual datums within a series, it probably isn’t, in which case Toyplot leaves it up to you to decide what you want, by passing a (label, marker) tuple to the legend.

Cheers,
Tim
