### ISSUE TITLE
target attribute dropped from <a> tags

### ISSUE THREAD

**Issue by kmorel** [sandialabs/toyplot#192]
I was using toyplot to create plots in a Jupyter notebook and wanted to create links to external web pages. I was pleasantly surprised that adding `<a>` HTML tags in text creates the links I want. However, I'd like the links to open up in a new tab/window so I don't have to worry about leaving my Jupyter notebook before it saves its state. I do this by adding a `target="_blank"` attribute to the `a` tag. Unfortunately, the `target` attribute seems to be dropped from the rendered SVG.

As an example, consider the following block of code run in Jupyter.

```python
canvas = toyplot.Canvas()
axes = canvas.cartesian()
axes.text(0, 0, '<a href="https://github.com/sandialabs/toyplot" target="_blank">Awesome plotting</a>')
```

When you click on the text, the browser tries to leave the current page rather than opening up a new tab/window.

**Comment by tshead2** [comment]
The target attribute is now supported in master.
