### ISSUE TITLE
MemoryError: Unable to allocate array with shape (2146795575, 2) and data type int64

### ISSUE THREAD

**Issue by studiocardo** [sandialabs/toyplot#195]
Hi

First of all, thanks for creating toyplot!

I'm trying to visualize a community detecting in graph by following your example at (https://toyplot.readthedocs.io/en/stable/communities-case-study.html).  This is the perfect example for me since everything in the example matches exactly what I am trying to achieve.

The problem is that my graph size might be too big (1M edges).  And I think that created a 1Mx1M matrix for toyplot and generated a MemoryErr.

So I cast the array to UINT16, hoping to circumvent the MemoryErr.  Though it went through without an error msg, it ground the machine to a halt without yielding a plot.

Any suggestion on how to best approach a data input of this size?  Realistically, it makes little sense to try to plot all of edges since there's no way one can see that details, but it is only the first step.  I will provide the ground truth data next so it can detect the communities and help visualize the communities, which is the ultimate goal of this exercise...

Thank you for your input! 

SH

**Comment by tshead** [comment]
@studiocardo - Thanks for the kind words.  All Toyplot plots start out as SVG images, so I imagine that your browser is grinding to a halt, trying to store and rasterize 1M SVG lines, which require much more storage than a matrix (as an aside, I don’t recall using any adjacency matrices in the implementation).

So the short answer is “don’t do that”.  After doing some large scale graph visualization in the oughts, I’m firmly of the opinion that rendering huge graphs is of mainly aesthetic value.  For insight, you need to think about summarization, e.g. run community detection and render just the communities (or the meta-communities, or the meta-meta-communities, or whatever).

Cheers,
Tim
