### ISSUE TITLE
showing x-axis and y-axis in matrix tooltip

### ISSUE THREAD

**Issue by the-oaks** [sandialabs/toyplot#196]
is there an easy way to also show the x-axis and y-axis in addition to the value in the tooltip (when hover over mouse) in the matrix plot? this will be very useful in a big matrix. thanks

**Comment by tshead2** [comment]
@the-oaks - Not sure if this is addressing your question or not, but you can supply your own title on a per-cell basis.  Here's a made-up example:

```
import numpy
import toyplot

data = numpy.random.normal(size=(4,4))

canvas, table = toyplot.matrix(data)
for i, row in enumerate(data):
    for j, value in enumerate(row):
        table.body.cell[i,j].title = f"({i},{j}) {value:.3f}"
```

Let me know if this helps,
Tim
