### ISSUE TITLE
Package license file with source distribution

### ISSUE THREAD

**Issue by synapticarbors** [sandialabs/toyplot#197]
It would be helpful to include the license file in the source distribution. I've mostly seen this done by including a `MANIFEST.in` file with the `include` line for the license.

**Comment by tshead2** [comment]
@synapticarbors: thanks for the tip!  I've pushed this in master.  Are you pulling from GitHub or PyPi, out of curiosity?

**Comment by synapticarbors** [comment]
It looks like the recipe is pulling from pypi

**Comment by tshead2** [comment]
Fair enough.  I'll put out a new PyPi release soon, so it'll start working for you.

Cheers,
Tim

**Comment by synapticarbors** [comment]
Thanks for doing this

**Comment by tshead2** [comment]
Just released Toyplot 0.19.0 on PyPI, incorporating these changes.  Let me know if there are further problems.

Cheers,
Tim
