### ISSUE TITLE
Efficient plotting

### ISSUE THREAD

**Issue by pulkin** [sandialabs/toyplot#198]
Say, I am working in jupyterlab. How do I efficiently render a large chunk of data? Whether I use native integration or render `png` it is too slow.
```python
canvas = toyplot.Canvas()
ax = canvas.cartesian()
x = np.random.rand(10000)
y = np.random.rand(10000)
ax.scatterplot(x, y)
data = toyplot.png.render(canvas)
print("done")
```

**Comment by tshead** [comment]
Unfortunately I don’t have a satisfying answer for you … Toyplot is optimized for high quality (SVG / PDF) output, but that tends to make it slow - also, the PNG backend actually creates an SVG figure, then rasterizes it, so it’s not going to be any faster.

Cheers,
Tim
