### ISSUE TITLE
Support arrow >= 1.0

### ISSUE THREAD

**Issue by gavinhodge** [sandialabs/toyplot#199]
There are some breaking changes in the arrow 1.0 release. I noticed when using toyplot.locator.Timestamp, as the `ticks()` function will crash.

Toyplot doesn't pin the arrow dependency, so pip will install the latest version by default.

Notably, `timestamp` has been renamed to `int_timestamp`, and replaced by a function `timestamp()`. So the various tick generators need to either reference `int_timestamp` or call `timestamp()`.

I'm not sure which is better for backwards compatibility.

**Comment by gavinhodge** [comment]
Arrow v1.0 migration guide:
https://github.com/arrow-py/arrow/issues/832

**Comment by tshead2** [comment]
@gavinhodge - many thanks for this, will work on a fix right away.

Cheers,
Tim

**Comment by jdtuck** [comment]
@tshead2 Do we have a fix for this? since it is not pinned and arrow has gone to 1.2 makes it a pain to just install it.

**Comment by tshead2** [comment]
Fixed in e0cf9da895c26996d4a959f654b7a5ba87ce7f3b.
