### ISSUE TITLE
Add graph visualization to the API.

### ISSUE THREAD

**Issue by tshead2** [sandialabs/toyplot#44]
We now have a basic mark for rendering graphs.  Missing in the current implementation:

- [x] Harmonize the API for specifying vertex / edge attributes with the plot / scatterplot API.
- [x] Support edge splines.
- [x] Specify graphs using just edges (create induced vertices automatically).
- [x] Allow arbitrary edge types, not just integer ids.
- [x] At least one high quality tree layout algorithm.
- [x] At least one high quality graph layout algorithm.
- [x] An option to explicitly specify vertex coordinates, so we can lay-out a graph once, and display it multiple times with a consistent layout.
- [ ] Start / end markers to show edge direction.
- [x] Vertex labelling

**Comment by tshead** [comment]
I'm really liking Lombardi layouts for the default: http://lombardi.cs.arizona.edu/downloads.html

**Comment by tshead2** [comment]
All the basics are in place, will switch to individual issues for ongoing work.
