### ISSUE TITLE
Python 3 compatibility issue?

### ISSUE THREAD

**Issue by davidtrem** [sandialabs/toyplot#50]
Toyplot looks pretty interesting. Unfortunately I did not yet manage to make it work on my environment.
I'm using python 3.4 from Macports on my Mac OS 10.10.3  . Using latest Ipython 3.x branch (but also tested unsuccessfully with earlier version 3.1 and 3.2). I get the following warning that seems to also prevent proper display in the notebook:

    .../python3.4/site-packages/IPython/core/formatters.py:360: FormatterWarning: text/html formatter returned invalid type <class 'bytes'> (expected (<class 'str'>,)) for object: <toyplot.canvas.Canvas object at 0x1058b6518>
    FormatterWarning

Is this related to a python 3 compatibility issue ?
Any help/suggestion/... would be appreciated.

**Comment by tshead2** [comment]
@davidtrem - Thanks for your interest.  We do continuous integration testing with Python 3.3 and Ubuntu 12 on travis-ci, but I'm sure there are subtleties I've overlooked.  I use Macports and Python 2.7 for development, so this ought to be easy enough to reproduce.

Cheers,
Tim

**Comment by tshead2** [comment]
@davidtrem - I was able to reproduce this without any trouble, and committed a fix.  Many thanks for the feedback!

Closed in d027798e5fcf44b5b995586209f2fe75950b0a6a

**Comment by davidtrem** [comment]
Great ! That works now :-)
Thanks.
