### ISSUE TITLE
Explore error bars.

### ISSUE THREAD

**Issue by tshead2** [sandialabs/toyplot#52]
Are error bars a new type of mark?  An additional feature in the plot() API?  A new type of marker?

**Comment by tshead2** [comment]
Happy to have someone working on this, but I won't get to in the foreseeable future.

**Comment by janxkoci** [comment]
Well it would be nice to have a parameter for error bars in `bars()`. The code could even be reused for implementing boxplots (aka box and whisker plots). I'm not good in python (one reason why I care about toyplot to begin with :wink: ) so I probably cannot help much with the programming, but I wanted to give this issue some kind of upvote.

**Comment by tshead2** [comment]
Thanks for the feedback; in the meantime, you can supply boundaries to `bars()`, and superimpose scatterplots to produce something a lot like a box plot.
