### ISSUE TITLE
TypeError: Cannot change data-type for object array.

### ISSUE THREAD

**Issue by ShanSabri** [sandialabs/toyplot#53]
TypeError when trying to run a render: 

#!/usr/bin/env python
import numpy, toyplot
x = numpy.linspace(0, 1)
y = x ** 2
canvas = toyplot.Canvas(width=300, height=300)
canvas.axes().plot(x, y)

**Comment by ShanSabri** [comment]
Specific error:  
File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/lib/stride_tricks.py", line 32, in as_strided
    array.dtype = x.dtype
TypeError: Cannot change data-type for object array.

**Comment by tshead2** [comment]
@ShanSabri : Thanks for the error output, I was about to ask :)  I suspect that the numpy version may be the problem, could you post the output of

     import numpy
     print numpy.__version__

Many thanks,
Tim

**Comment by tshead2** [comment]
@ShanSabri : FYI, Toyplot requires numpy >= 1.7.  If you install with pip or easy_install it should enforce this, but in case you didn't, I added a runtime check for the numpy version.

**Comment by ben-albrecht** [comment]
I am getting the same error with Python 2.7.6, NumPy 1.8.0rc1

**Comment by tshead2** [comment]
Hmmm ... I'll see if I can reproduce this - my Macs are all currently on Numpy 1.9.2, but there's nothing special about it (or so I thought).

**Comment by neb1215** [comment]
I have the same error with numpy 1.8.0. Upgrading to the latest build fixed the issue.

**Comment by tshead2** [comment]
Just as a heads-up to everyone that I setup an environment to reproduce this, and am looking at it now.

**Comment by tshead2** [comment]
Closed in 38159a84c3261ffb948fcea164fa87e4b20f650a ... please post feedback if you have any new issues.

Thanks,
Tim
