### ISSUE TITLE
Add section to user guide for Embedding plots or remove/alter quotation from tutorial "Toyplot figures are beautiful, scalable, embeddable, and interactive" from tutorial

### ISSUE THREAD

**Issue by mgrady3** [sandialabs/toyplot#54]
I would be interested in learning how to embed toyplot figures into other constructs like a PyQt gui.

There are many guides for embedding matplotlib figures/canvases into GUI's - I'd imagine it could be done with toyplots.

If its not possible, however, I suggest you remove/reword the quotation about the plots being embeddable from your tutorial on readthedocs

**Comment by tshead** [comment]
@mgrady3 : Thanks for the feedback!  I'll do a bit of both ... when I wrote "embeddable", what I really meant was "self-contained HTML that doesn't require a server to function" ... you can take the output from toyplot's HTML backend and drop it into a document without having to modify the document, and it will Just Work whether you have a network or not.  This is one of the areas where Toyplot is explicitly unlike other libraries.  So, I'll clarify that.

In addition, I'm not a Qt expert, but I put together a quick example in `toyplot/design/qt-embedding.py` to get you started.  Note that the example contains code to embed an SVG in a QWebView, a PNG in a QWebView, and HTML in a QWebView, but the last one doesn't work for some reason - I can use the inspector to see that the content is there, but for some reason it's invisible.  You can imagine other ways to do the embedding - PNG to QImage, SVG to QSvgWidget, etc.

Cheers,
Tim

**Comment by tshead2** [comment]
Digging deeper, when pulling Toyplot HTML into QWebView, the DOM isn't parsed correctly - sibling elements of <clipPath> in the HTML become children of <clipPath> in the DOM, which explains their lack of visibility.  This appears to be an issue with Qt 4.8.7 that I used for testing, and/or the version of WebKit that it embeds.  Will try again with PyQt5.

**Comment by mgrady3** [comment]
Thanks again

**Comment by tshead2** [comment]
With PyQt5, Toyplot HTML output works great.  I'll be writing everything up in a new "Embedding" section of the user guide in the next few days.

**Comment by tshead2** [comment]
Added a new section on embedding to the user guide at http://toyplot.readthedocs.org/en/latest/embedding.html
