### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by ebressert** [sandialabs/toyplot#57]
Are there plans to implement WebGL capabilities? It would be ideal for plots where +10k points are going to be plotted.

**Comment by tshead** [comment]
@ebressert - you know I hadn't ever really considered WebGL, or even Canvas for that matter.  It would definitely be technically feasible, though I don't know if I would ever get around to it - my interest is in the interaction (I have many plans beyond the simple interactions we have today).  Contributions welcome!

Cheers,
Tim

**Comment by ebressert** [comment]
Not sure if I have time to contribute on the idea, but if the times comes up I'll look into it. For me, WebGL would make this application be more responsive, thus more interactive.
