### ISSUE TITLE
Possibility to remove the x/y "tooltip"

### ISSUE THREAD

**Issue by knightofni** [sandialabs/toyplot#62]
How can I hide the "tooltip" (i'm not sure of the correct term, it's that x / y area that I've circle in blue)? From what I've seen in the API, it doesn't seem supported by default. That would be a nice option (to achieve maximum cleanness of the chart). Could you give me a few pointers on how to achieve this ?

![toyplot_tooltip](https://cloud.githubusercontent.com/assets/3415960/8654539/6f7f6a6a-29bd-11e5-9209-d566487202a8.png)

Thanks

Nicolas

**Comment by tshead2** [comment]
@knightofni - It isn't obvious, but the coordinates are a property of the cartesian axes; you can disable them with

        axes.coordinates.show = False

This is documented in http://toyplot.readthedocs.org/en/latest/cartesian-axes.html, along with some other properties you can change for the interactive coordinates.

Cheers,
Tim

**Comment by tshead2** [comment]
Note to self: probably ought to start a dedicated section on "Interaction" in the user guide.

**Comment by knightofni** [comment]
Great, thanks a lot ! Going back to the doc, that's the place i had checked (http://toyplot.readthedocs.org/en/latest/toyplot.axes.html)
