### ISSUE TITLE
Create Qt-based backends for PNG and PDF.

### ISSUE THREAD

**Issue by tshead2** [sandialabs/toyplot#69]
Currently we use pango / cairo for our legacy output formats, but getting them built can be !#@$! difficult.  Explore whether we could use Qt (whether PyQt or PySide) to accomplish the same thing.

**Comment by tshead** [comment]
It turns out that fixing #73 makes this look very doable.

**Comment by tshead2** [comment]
It turns out that QSvgRenderer only supports the SVG 1.2 Tiny profile, which may-or-may-not be a problem.  We'll have to see whether the tiny profile includes everything we want to use in our figures.

An alternative would be to use the webkit support in Qt to render SVG files, since it supports a wider range of valid SVG.  However, I don't know yet whether we can render from webkit to PDF or just to bitmap images.

**Comment by tshead2** [comment]
After looking at http://www.w3.org/TR/SVGMobile to see what is-and-isn't supported, I'm inclined to lean away from the SVG Tiny profile - it lacks a *lot* of stuff that we're taking for granted.

**Comment by tshead2** [comment]
So far, the only issue is generating PDF and PNG files with transparent backgrounds - the current toolchain that converts from QWebPage to the target format always produces an opaque white background.

**Comment by tshead2** [comment]
Closed in 8734d7a5135852e4cc6043173a3119cef1e78c3d.

**Comment by cmorgan** [comment]
awesome! Cairo install on Windows (no choice) is double  !#@$! difficult.

**Comment by tshead2** [comment]
@cmorgan - it would be good to get feedback on how well this works for you ... between PyQt5, PyQt4, and PySide it's still a complicated world out there ...
