### ISSUE TITLE
python style print statement in png.py

### ISSUE THREAD

**Issue by knightofni** [sandialabs/toyplot#72]
Not a very exciting bug, but it does stop execution

line 114 of cairo.py

  File "/Users/nicolas/anaconda/envs/principes3.4/lib/python3.4/site-packages/toyplot-0.6.0-py3.4.egg/toyplot/cairo.py", line 114
    print "Unhandled clip tag: %s" % child.tag
                                 ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by tshead2** [comment]
@knightofni - thanks for this!  It's fixed in master.

Cheers,
Tim
