### ISSUE TITLE
SVG colors disappear when imported to inkscape

### ISSUE THREAD

**Issue by dereneaton** [sandialabs/toyplot#73]
This might be an inkscape problem. I've found that figures I export with toyplot.svg.render() are not compatible with inkscape, which seems unable to import their colors.

**Comment by tshead2** [comment]
Interesting ... does that mean that it produces a recognizable plot, but without color?  If you could attach some before / after screenshots that would be useful.  Also, which version / platform for Inkscape?

Many thanks,
Tim

**Comment by dereneaton** [comment]
Hi Tim, 
I'm using Inkscape 0.48.3.1 r9886 (Jan 29 2013) and Toyplot 0.6.0. 
Below is the svg image which looks fine in an image viewer, and below that is the same svg file when it is either opened with or imported into inkscape. 

![image](https://cloud.githubusercontent.com/assets/5395480/8882405/9cbd7210-3214-11e5-81a7-8e990a446be2.png)

![image](https://cloud.githubusercontent.com/assets/5395480/8882423/bc3467f2-3214-11e5-95a6-7d7f5034bfb2.png)

I'm really loving toyplot so far, it's very intuitive. 

-D.

**Comment by tshead2** [comment]
Deren:

Thanks for the quick followup, I'll see if I can reproduce this.  Of course it might just be an Inkscape bug, but Toyplot tries to "play well with others", so I'll see if there's something we should be doing differently.

As an aside, you might consider using the "step" parameter with your call to matrix() to thin-out the row and column indices.

Cheers,
Tim

**Comment by tshead2** [comment]
Interestingly, importing into Illustrator CS 6 produces the same effect.

**Comment by tshead2** [comment]
I'm able to reproduce this behavior in Inkscape 0.91.  Some playing around with the builtin XML editor in inkscape suggests that it does not support "rgba()" style CSS colors.  "rgb()" seems to work.

**Comment by tshead** [comment]
@dereneaton - I just pushed a fix for this to master.  It turns out that lots of apps / libraries don't respect rgba() colors in SVG.  This clears-up a longstanding mystery with Qt rendering too, so thanks again for the report, it was a big help!

Cheers,
Tim
