### ISSUE TITLE
Add viewbox property in SVG declaration (for IE)

### ISSUE THREAD

**Issue by kenrick95** [sandialabs/toyplot#74]
When displaying SVG file generated with toyplot in IE in different size than the original SVG size, IE crops the image instead of resizing it. [The accepted solution from StackOverflow is to add viewbox property in the SVG declaration.](http://stackoverflow.com/a/15905747/917957) So can you add this to toyplot (instead of having to manually open the svg file and adding that particular code)? Thanks.

**Comment by tshead2** [comment]
Sounds reasonable, I'll check into adding it.  Thanks for the heads-up ...

Cheers,
Tim

**Comment by tshead2** [comment]
@kenrick95 - I'm having a little trouble reproducing this, which version of IE are you using, and how are you altering the size of the original SVG?  If you could post a sample HTML document that demonstrates the cropping that would be ideal.

Thanks,
Tim

**Comment by kenrick95** [comment]
![capture-toyplot-ie](https://cloud.githubusercontent.com/assets/3090380/8975037/bc8acc0a-36ab-11e5-8d32-2cd3431b00a8.PNG)

For demo: `test.html`
```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <title>test</title>
</head>
<body>
    <h1>Original</h1>
    <img src="test.svg">
    <table>
        <tr>
        <td width="500">
            <h1>Resized</h1>
            <img src="test.svg" width="500" height="150"></td>
        <td width="500">
            <h1>With viewbox</h1>
            <img src="test viewbox.svg" width="500" height="150">
        </td>
        </tr>
    </table>
    
    
</body>
</html>
```

The difference between `test.svg` and `test viewbox.svg` is highlighted here:
![capture-test-viewbox](https://cloud.githubusercontent.com/assets/3090380/8975088/42984778-36ac-11e5-9663-258c052b4cdc.PNG)

**Comment by tshead2** [comment]
A good reference to understand what viewBox does:

http://sarasoueidan.com/blog/svg-coordinate-systems/

**Comment by tshead2** [comment]
@kenrick95 - I don't have a copy of IE handy to test it, but I've pushed this change to the "viewbox" branch if you want to check it out.  I'm also setting the preserveAspectRatio attribute to "xMidyMid meet", which is supposed to be the default, but which wasn't on Firefox.  So now it should be doing what you expect, on all browsers.  Let me know.

One thing I forgot to mention earlier - the HTML and SVG backends are designed to make it (relatively) easy to tweak the markup programmatically if necessary.  For example:

```
import xml.etree.ElementTree as xml
canvas, axes, mark = toyplot.plot(x, y)
svg = toyplot.svg.render(canvas) # Returns the DOM
svg.viewBox = "0 0 %r %r" % (canvas._width, canvas._height)
svg.preserveAspectRatio = "xMidyMid meet"
open("test.svg", "w").write(xml.tostring(svg))
```

**Comment by tshead2** [comment]
Closed in aaf7fd2723bea847b728ab8db42e5feb3c8c28d2.

**Comment by kenrick95** [comment]
Thanks :smile:

**Comment by tshead2** [comment]
One other thing - you'll want to keep an eye on #76, which I discovered while working on this issue.
