### ISSUE TITLE
Show data point values on hover

### ISSUE THREAD

**Issue by kmatt** [sandialabs/toyplot#75]
The X/Y coordinates of the mouse hover location approximate the values of a point, but many users prefer to see the specific source data values. Is this an option for interactive charts?

**Comment by tshead** [comment]
@datasaur - not yet, but definitely on my personal wish list.  Contributions welcome!

Cheers,
Tim

**Comment by kmatt** [comment]
One approach is to use the plot title with a value of the data point:

    axes.plot(df[column], title=df[column])

**Comment by tshead2** [comment]
Quoting @kmatt (not sure why this showed-up in my email and not in the issue):

    One approach is to use the plot title with a value of the data point:
    axes.plot(df[column], title=df[column])

**Comment by kmatt** [comment]
I backed the comment out because it turned out not to work as I implemented it. All data points had the same value in the popup across a series.

**Comment by tshead2** [comment]
Actually that's a bug, so I'm glad you brought it up.  See #82.

Leaving this item open because it's really about a new interaction feature, one that would display datum values, interpolate in-between values on a plot, etc.

**Comment by tshead2** [comment]
@kmatt - FYI, per-datum titles work properly in Toyplot 0.8.0.  Still no substitute for true interaction (I find that browser support for SVG titles is a bit flaky).
