### ISSUE TITLE
Axis label rotation?

### ISSUE THREAD

**Issue by kmatt** [sandialabs/toyplot#79]
Can labels on the x-axis be rotated vertically instead of horizontally?

When working with date based timeseries, and following the approach on http://toyplot.readthedocs.org/en/latest/tick-locators.html, labels are overlapping. Vertical labels allow more tick locators without overlap.

**Comment by tshead2** [comment]
@kmatt - Yep, this is doable.  There's a list of editable properties for cartesian axes located at  http://toyplot.readthedocs.org/en/latest/cartesian-axes.html, plus I've added an example with rotated labels at the bottom of the page you were looking at: http://toyplot.readthedocs.org/en/latest/tick-locators.html.

Many thanks for asking!

Tim

**Comment by tshead2** [comment]
Closed by 618d066e765c1b413b820020414962584a7cec1d
