### ISSUE TITLE
Provide API to override the default CSV export filename.

### ISSUE THREAD

**Issue by kmatt** [sandialabs/toyplot#81]
When multiple series are plotted, a csv export of the series is named by default "toyplot.csv". 

If the plot title or other attribute was used (defaulting to "toyplot") exports would be easier to identify / use.

Is there a data series attribute that can be passed to the JS that saves the data to a file?

**Comment by tshead2** [comment]
It's a reasonable request; I'd probably add a new attribute for this, since there can be multiple series / titles associated with a single plot / file.

**Comment by tshead2** [comment]
@kmatt - I've added some new API to do this in master.  Checkout the bottom of the page at http://toyplot.readthedocs.org/en/latest/interaction.html for an example.

**Comment by kmatt** [comment]
Thanks! I shall put it to use ASAP.
