### ISSUE TITLE
Data Table formatter error in IPython Notebook

### ISSUE THREAD

**Issue by kmatt** [sandialabs/toyplot#84]
Using the example from http://toyplot.readthedocs.org/en/latest/data-tables.html, IPython Notebook throws an error. Is this an issue with Toyplot, IPython, or my usage of them?

    import toyplot.data
    import numpy
    table = toyplot.data.Table()
    table["x"] = numpy.arange(10)
    table["x*2"] = table["x"] * 2
    table["x^2"] = table["x"] ** 2
    table 

    //anaconda/envs/py34/lib/python3.4/site-packages/IPython/core/formatters.py:360: FormatterWarning: text/html formatter returned invalid type <class 'bytes'> (expected (<class 'str'>,)) for object: <toyplot.data.Table object at 0x107d53898>
      FormatterWarning

**Comment by kmatt** [comment]
This might be a Python 3 issue, as I have the example working fine under a Python 2.7 Notebook. Related to #50 ?

**Comment by tshead2** [comment]
Yep, you beat me to it - this is almost certainly another example of the problem fixed in #50, not to mention a gap in our testing.

**Comment by tshead2** [comment]
Fixed in 39c6194e67ae3ff812e1cce9302febbdc811b614
