### ISSUE TITLE
HTML backend for Data Tables

### ISSUE THREAD

**Issue by kmatt** [sandialabs/toyplot#85]
It appears that a data table cannot be rendered with toyplot.html.render ?

The idea here would be to offer the same CSV export popup as with a canvas, so tabular data can be exported from a web page the same as with a chart.

**Comment by tshead2** [comment]
So, the way to render data tables is with table axes, see http://toyplot.readthedocs.org/en/latest/table-axes.html for details.  Table axes don't support CSV export at the moment, but that's already on the TODO list, see #42.

**Comment by tshead2** [comment]
Also worth mentioning is #17.
