### ISSUE TITLE
Provide more control over matrix axis labels.

### ISSUE THREAD

**Issue by dereneaton** [sandialabs/toyplot#86]
I've been playing with matrix visualization in toyplot and encountered several questions that I couldn't figure out from the documentation. 

How to:
- turn off or edit axis labels on a matrix plot
- access values in the table/matrix (table.body.cell(i,j)?). 
- put matrix on a canvas grid with other plots.

As an example: I've been trying to edit hover labels on a heatmap to include names, here:
http://nbviewer.ipython.org/gist/dereneaton/c8292a8febc758eb0438/toy_heatmap.ipynb

**Comment by tshead2** [comment]
@dereneaton - I added a couple of new examples to the matrix visualization section of the user guide at http://toyplot.readthedocs.org/en/latest/matrix-visualization.html, let me know if that helps.

There is a definite action item here, to make it easier to turn-off the default axis labels, I'll see if can crank that out in the next couple of days.

As an aside, graph / tree plots will likely be the next new visualization type to make it into the library.  There is experimental support in master if you're interested.

**Comment by tshead2** [comment]
@dereneaton - Just a heads-up that I've committed a couple of new parameters for turning-off the labels in master, and updated the documentation at http://toyplot.readthedocs.org/en/latest/matrix-visualization.html to match.

Cheers,
Tim
