### ISSUE TITLE
is it possible to animate a matrix?

### ISSUE THREAD

**Issue by cmorgan** [sandialabs/toyplot#91]
looks like AnimateFrame acts only on  toyplot.mark.BarBoundaries, toyplot.mark.BarMagnitudes, toyplot.mark.Plot, toyplot.mark.Text. Any ideas for how i could use the Animation scaffolding to animate a matrix?

**Comment by tshead** [comment]
Yeah, it's telling that none of the animation currently allows you to change data values, only styles - see #7.

You could approach this in a couple of ways.  The "low hanging fruit" way would be to add a new method to `toyplot.canvas.AnimationFrame`, say `set_table_bstyle()`, add support for it in `toyplot.html.apply_changes()`, and corresponding Javascript code in `toyplot.html._animation_controls`.  With that in place, you could change the background color of any table cell to suit, however you'd be doing the color mapping yourself for any modified cells.

The "doing it right in the long term" approach would be to have some sort of `set_table_data()` function, but then the color mapping needs to be marshaled into Javascript too.  There's also the problem of correct behavior - if, over the course of the animation, you change the domain, should the color mapping change globally to match, or remain static (or something else)?  There are use-cases for both behaviors.
